[package]
name = "rust-effects"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
ratatui = { version = "0.30.0", default-features = false }
color-eyre = "0.6.5"
ratzilla = "0.2.0"
tachyonfx = { version = "0.19.0", default-features = false, features = [
  "web-time",
] }
